SPA on React
Useit14/Useit14-web_bee_task1_React.io pull request #1
Opened 2022-07-26 10:56 UTC by Useit14

2022-07-26 18:14 UTC, crutch12 commented
https://codesandbox.io/s/practical-morning-mkpumu

2022-07-26 18:14 UTC, crutch12 commented
отдал @stilwuc

2022-07-26 18:14 UTC, Useit14 commented
https://codesandbox.io/s/practical-morning-mkpumu
https://mkpumu.csb.app/index

2022-07-29 08:56 UTC, Stilwuc requested changes

2022-07-29 08:56 UTC, Stilwuc commented on README.md
> +# Useit14-web_bee_task1_React.io
Верстка немного на карте поплыла, и лоадер постоянно отображается.
![image](https://user-images.githubusercontent.com/44724024/181710977-61a58bf1-7896-4cd3-bc33-bed6ff08026c.png)

2022-07-29 08:56 UTC, Stilwuc commented on README.md
> +# Useit14-web_bee_task1_React.io
Если плейнуть таймер один раз, перейти на другую вкладку вернутся и плейнуть таймер еще раз, то будет прикольный визуальный мув при count + 1
![chrome-capture-2022-6-29](https://user-images.githubusercontent.com/44724024/181711666-f38c7ec5-2b04-4c1d-9134-1c09d6513899.gif)

2022-07-29 08:56 UTC, Stilwuc commented on package.json
> +    "images": "^3.2.4",
Хм, интересно, юзаешь где нибудь?)

2022-07-29 08:56 UTC, Stilwuc commented on src/components/Timer/Timer.js
> +import refresh from './refresh.png'
По поводу картинок, обычно они не смешиваются с компонентами(одна и та же папка), и разделяются либо в отдельную папку assets, либо в public и абсолютные ссылки в src.
В твоем случае лучше первый вариант, так как юзаешь как src import
Но в принципе я понял что ты хотел сделать, своего рода группировка по сущностям, так что можешь так оставить, я чисто подсветил как это чаще всего выглядит в проектах

2022-07-29 08:56 UTC, Stilwuc commented on src/App.css
> +    text-decoration: none !important;
`!important` не стоит юзать, тем более если у тебя селектор по тегу, перепоределить такие стили будет сложно, в данной ситуации по идее и без импортанта ок.
Но если у тебя есть стили которые переопределяют вот этот стиль, добавь селектору веса

2022-07-29 08:56 UTC, Stilwuc commented on src/App.css
> +#avatar img {
Немного про стили общим комментом напишу)
1. Старайся названия классов(да и не только классов, а вообще в принципе) держать в одном стиле, а то сейчас у тебя где то `kebab-case` где то `camelCase`, где то и то и то
2. Селекторы по id не очень, он более весомый, и по умолчанию юзаем селекторы по классам, а по id как исключение
3. С единицами измерения тоже унифицированно подходить, а то в тех же margin у тебя где то px, где то rem
4. Писать все стили приложения в одном глобальном css файле не очень, скоупа применения нету, каждый стиль глобален, и идет в бандл, лучше заюзать styled-components или  css модули (это скорей на будущее, просто подсвечиваю как правильно делать)

2022-07-29 08:56 UTC, Stilwuc commented on src/App.css
> +    /* identical to box height */
Вот эти комменты выглядят не очень полезно, да еще и разделители в две пустых строчки после жестко)
Я бы выпилил

2022-07-29 08:56 UTC, Stilwuc commented on src/App.css
> +
И тут и в js есть косячки по форматированию, не буду все перечислять, советую просто претиер настроить и пройтись по всем файлам чтобы было красиво

2022-07-29 08:56 UTC, Stilwuc commented on src/App.css
> +        width: 85% !important;
Такие брекпоинты не сильно полезные, ты бы это мог решить и без них, viewPort единицы измерения, проценты от родительского блока и тд

2022-07-29 08:56 UTC, Stilwuc commented on src/components/Timer/Timer.js
> +        const seconds = document.getElementById('seconds');
Ты заюзал реакт но пользуюшься им чисто для jsx и значения верстки обновляешь нативно, не совсем правильно.
В React есть useState, заюзай его

2022-07-29 08:56 UTC, Stilwuc commented on src/components/Timer/Timer.js
> +            imgCollapse.classList.toggle('arrow-up')
Вот эти динамические стили тоже стоит делать через React
(Не буду пока больше подсвечивать где надо на рект заменить, как поправишь еще раз пройдусь)

2022-07-29 08:56 UTC, Stilwuc commented on src/components/Timer/Timer.js
> +                            <img src={close} alt=''/>
Если close не работает то лучше не рендерить его

2022-07-29 08:56 UTC, Stilwuc commented on src/components/Timer/Timer.js
> +        clearInterval(timerId);
clearInterval надо еще делать на unmount, а то будет как я в начале кидал скрин, несколько setInterval перебивают друг друга (да и память потечет)

2022-07-31 19:05 UTC, Useit14 commented
https://codesandbox.io/s/competent-curran-y3m6dn
https://y3m6dn.csb.app/index

2022-08-02 09:12 UTC, Stilwuc requested changes

2022-08-02 09:12 UTC, Stilwuc commented on src/components/Timer/Timer.js
> +                                <img onClick={() => props.setCountSeconds(props.countSeconds + 1)} src={play} alt=''/>
При множественном клике на эту кнопку опять флекс начинается
![chrome-capture-2022-7-1](https://user-images.githubusercontent.com/44724024/182185487-2a006ca7-c489-499d-bf0d-768f95fd84da.gif)

2022-08-02 09:12 UTC, Stilwuc commented on src/App.css
> +    background: #F5F5F5 !important;
Все еще много important, они действительно все нужны?
![image](https://user-images.githubusercontent.com/44724024/182327532-0ca34520-5d80-46ae-9d0b-158a260183f7.png)

2022-08-02 09:12 UTC, Stilwuc commented on src/components/Timer/Timer.js
> +                                <img onClick={() => refreshTimer()} src={refresh} alt=''/>
Если два раза на refresh нажать таймер стопнется
![chrome-capture-2022-7-2](https://user-images.githubusercontent.com/44724024/182327948-3bc3d1e9-fcf3-434f-9135-51d8b8bd8924.gif)

2022-08-02 09:12 UTC, Stilwuc commented on src/components/Timer/Timer.js
> +            setShow('show')
Так как show у тебя бинарный, то имеет сделать стейт true/false и в верстке сделать
```
<div id="collapse-post-content2" className={`timer map-collapse collapse ${show ? 'show' : ''}`}>
```

2022-08-02 09:12 UTC, Stilwuc commented on src/components/Timer/Timer.js
> +            setShow('show')
Arrow соответсвенно тоже можно подвязать на тот же обновленный стейт `show`

2022-08-02 09:12 UTC, Stilwuc commented on src/components/Timer/Timer.js
> +                        <span id="seconds">{props.seconds}</span>
тебе же теперь Id не нежны тут(ну и в других местах проверь)

2022-08-02 09:12 UTC, Stilwuc commented on src/App.js
> +    const [countSeconds, setCountSeconds] = useState(0)
Зач тебе 4 стейта, когда ты можешь заюзав один стейт вычислять значения в runtime для других.
Типо храним всегда количество прошедших секунд, и на основе этого minutes = /60 и тд

2022-08-02 09:12 UTC, Stilwuc commented on src/components/Header/Header.js
> +    const [show, setShow] = useState(' ')
Тут тоже на boolean подвяжись

2022-08-02 09:12 UTC, Stilwuc commented on src/components/Header/Header.js
> +}
Все еще есть проблемы с форматированием, `;`, ординарные строчки в атрибутах тегов, спейсы лишние и тд

2022-08-02 09:12 UTC, Stilwuc commented on src/components/Map/Map.js
> +            preloader.classList.add('map-preloader-hidden');
вот это по стейту в className ставь

2022-08-02 09:12 UTC, Stilwuc commented on src/components/Map/Map.js
> +                                    <img src={close} alt=''/>
Удали, не работает

2022-08-02 09:12 UTC, Stilwuc commented on src/components/Map/Map.js
> +                                onLoad={() => mapLoad}
Так ты не вызываешь функцию а просто на onLoad возвращаешь функцию.
Надо либо так
```suggestion
                                onLoad={mapLoad}
```
Либо так
```suggestion
                                onLoad={() => mapLoad()}
```

2022-08-02 18:41 UTC, Useit14 commented
https://codesandbox.io/s/mystifying-hofstadter-i2qjof
https://i2qjof.csb.app/index

2022-08-03 10:39 UTC, Stilwuc requested changes
Ластовые :)

2022-08-03 10:39 UTC, Stilwuc commented on src/App.css
> +    background: #F5F5F5 !important;
Разобрались, это для перепопределения стилей bootstrap.
Через sass переменные можно было бы задать, но так как тут чистый css, я считаю допускаемо(разок), но в будущем не пропущу такое)

2022-08-03 10:39 UTC, Stilwuc commented on src/components/Header/Header.js
> +                {' '}
Выглядит как не нужно

2022-08-03 10:39 UTC, Stilwuc commented on src/components/Header/Header.js
> +          <svg
Свг инлайном обычно не оч вставлять.
Понимаю что тут было лень выносить в отдельный файл и тд, так что на будущее

2022-08-03 10:39 UTC, Stilwuc commented on src/components/Header/Header.js
> +            show == true ? 'show' : ''
Есть кстати либа, с помощью которой поудобнее работать с такими conditional классами, называется `classNames`

2022-08-03 10:39 UTC, Stilwuc commented on src/components/Header/Header.js
> +}
Проблемы на месте

2022-08-03 10:39 UTC, Stilwuc commented on src/components/Index/Index.js
> +  const [show3, setShow3] = useState(false);
Делать нейминг переменных с постфиксом индекса такое.
Правильней семантически называть похожие стейты.
Типо `[showNavigation, setShowNaviagtion]`, `[showForm, setShowForm]`

2022-08-03 10:39 UTC, Stilwuc commented on src/components/Map/Map.js
> +  const [show, setShow] = useState('show');
Тут забыл на boolean перевести

2022-08-03 10:39 UTC, Stilwuc commented on src/components/Timer/Timer.js
> +  const [seconds, setSeconds] = useState(0);
В этом комменте я имелл ввиду что тебе полностью 4 стейта не нужны, оставь один только.
И вместо вывода стейта minutes например тут в верстке заюзай `getMinutes()`
![image](https://user-images.githubusercontent.com/44724024/182586553-cb70194d-04b0-4257-9b4c-fc7f6b3ea6b9.png)

2022-08-03 10:39 UTC, Stilwuc commented on src/components/Timer/Timer.js
> +  });
useEffect без зависимостей нестабильная штука, так как будет тригерится при любом ререндере компонента.
Если построил таймер на таймауте то поставь в зависимости `props.setCountSeconds`

2022-08-03 10:39 UTC, Stilwuc commented on src/components/Timer/Timer.js
> +    if (show == true) {
Это все сократить можно в 
```
setShow(!show)
```

2022-08-03 15:30 UTC, Useit14 commented on src/components/Timer/Timer.js
> +    if (show == true) {
https://codesandbox.io/s/blissful-feather-hs1vlc
https://hs1vlc.csb.app/index

2022-08-03 16:15 UTC, Stilwuc approved these changes
Гуд, летим мержить 🚀

2022-08-03 16:23 UTC, merged